[build]
  publish   = "website"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_KEY,SUPABASE_URL,ADMIN_PBKDF2_HASH"

[[redirects]]
  from   = "/admin"
  to     = "/admin.html"
  status = 200

[[redirects]]
  from   = "/superadmin"
  to     = "/superadmin.html"
  status = 200

[[redirects]]
  from   = "/mis"
  to     = "/mis.html"
  status = 200
