import fitz

doc = fitz.open()
page = doc.new_page()

# Title
page.insert_text((50, 50), "Sample PDF for Testing", fontsize=24, color=(0, 0, 1))

# Subtitle
page.insert_text((50, 80), "Generated by Antigravity", fontsize=16)

# Paragraph 1
text1 = """This is a sample PDF document created to test the PDF to Editable Format converter.
It contains multiple blocks of text to demonstrate the layout analysis capabilities."""
page.insert_text((50, 120), text1, fontsize=12)

# Paragraph 2
text2 = """You should be able to edit this text in the web application. 
Try changing the content and observe how the blocks adjust automatically."""
page.insert_text((50, 180), text2, fontsize=12)

# Save
doc.save("sample.pdf")
print("sample.pdf created")
